/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_200614833;

import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mario
 */
public class Guii extends javax.swing.JFrame {

    /**
     * Creates new form Guii
     */
    public Guii() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Analisis");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if("".equals(jTextArea1.getText())){
            System.out.println("esta vacio");
            abrir();
        }else{
            //Si es un archivo que no se ha guardado
                if("".equals(nombreArchivo)){      
                    int res = deseaGuardar();
                    if(res==2){
                    }
                    else{
                        abrir();
                    }
                }
                //Archivo que se abrio y se modifico
                else{
                    String texto = ManejoDeArchivos.Cargar(nombreArchivo);   
                    if(texto.equals(jTextArea1.getText())){
                        //Ya fue guardado reiniciar atributos del editor
                        abrir();
                    }
                    else{
                        
                        int res = deseaGuardar();
                        if(res==2){
                        }
                        else{
                            abrir();
                        }
                    }   
                }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        analisis.analizar(jTextArea1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guii().setVisible(true);
            }
        });
    }
    
    
    AnalisisArbol analisis = new AnalisisArbol();
    FileFilter fileFilter = new FileNameExtensionFilter("Archivos del proyecto .hk .gk", "hk", "gk");
    private String nombreArchivo="";
    private String Texto="";
    
    
    private void abrir(){
                        
                        JFileChooser chooser = new JFileChooser();
                        chooser.setFileFilter(fileFilter);
                        chooser.showOpenDialog(rootPane);
                        if (chooser.getSelectedFile() != null) {
                            nombreArchivo = chooser.getSelectedFile().getPath();
                        }
                        if (!"".equals(nombreArchivo)) {
                            jTextArea1.setText(ManejoDeArchivos.Cargar(nombreArchivo));
                            Texto=ManejoDeArchivos.Cargar(nombreArchivo);
                            jTextArea1.setEnabled(true);
                        } else {
                            JOptionPane.showMessageDialog(rootPane,
                                    "No se abrio ningun archivo",
                                    "Abrir",
                                    JOptionPane.INFORMATION_MESSAGE);
                        }
    }
    
    private int deseaGuardar(){
        
        int res=JOptionPane.showConfirmDialog(rootPane, "¿Desea guardar los cambios?", null, WIDTH);

        if(res==0){
            JFileChooser chooser = new JFileChooser();
            chooser.setFileFilter(fileFilter);
            chooser.showSaveDialog(rootPane);
            if (chooser.getSelectedFile() != null) {
                nombreArchivo = chooser.getSelectedFile().getPath();
            }    
            ManejoDeArchivos.Guardar(nombreArchivo, jTextArea1.getText());
            JOptionPane.showMessageDialog(rootPane,
                    "Archivo Guardado con éxito",
                    "Guardar",
                    JOptionPane.INFORMATION_MESSAGE);    
            nombreArchivo="";
            jTextArea1.setText("");
            return 0;
        }
        else if(res==1){
            nombreArchivo="";
            jTextArea1.setText("");
            return 1;
        }
        else{
            //No hace nada es cuando le da cancelar
            return 2;
        } 
    }
    
    
                       
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
