
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 06 23:23:03 CST 2017
//----------------------------------------------------

package proyecto1_200614833.Analisis;

/** CUP generated class containing symbol constants. */
public class SimboloH {
  /* terminals */
  public static final int ccorchete = 42;
  public static final int allave = 39;
  public static final int igualigual = 37;
  public static final int tdesc = 14;
  public static final int cllave = 40;
  public static final int tcase = 20;
  public static final int tmax = 7;
  public static final int mod = 27;
  public static final int acorchete = 41;
  public static final int coma = 45;
  public static final int tif = 17;
  public static final int caracter = 51;
  public static final int iden = 50;
  public static final int numero = 49;
  public static final int menos = 25;
  public static final int menor = 34;
  public static final int tdecremento = 5;
  public static final int EOF = 0;
  public static final int mas = 24;
  public static final int error = 1;
  public static final int ultimo = 30;
  public static final int mayor = 33;
  public static final int taumento = 4;
  public static final int tmin = 6;
  public static final int or = 31;
  public static final int menorigual = 36;
  public static final int por = 22;
  public static final int telse = 19;
  public static final int tlength = 15;
  public static final int potencia = 26;
  public static final int cparentesis = 44;
  public static final int tthen = 18;
  public static final int radicacion = 28;
  public static final int tcalcular = 3;
  public static final int noigual = 38;
  public static final int mayorigual = 35;
  public static final int tproduct = 9;
  public static final int tpar = 12;
  public static final int aparentesis = 43;
  public static final int tasc = 13;
  public static final int and = 32;
  public static final int trevers = 10;
  public static final int tconcat = 46;
  public static final int dolar = 29;
  public static final int tindice = 47;
  public static final int tlet = 2;
  public static final int division = 23;
  public static final int asignacion = 21;
  public static final int tend = 16;
  public static final int tsum = 8;
  public static final int cadena = 48;
  public static final int timpr = 11;
}

